'use strict';

/**
 * src/middleware/errorHandler.js
 * Global error-handling middleware (4-argument Express signature).
 * Must be mounted LAST in app.js.
 *
 * Handles:
 *  - PostgreSQL errors  (unique violation → 409, not-null → 400, FK → 409, etc.)
 *  - JWT errors         (expired, invalid)
 *  - Multer errors      (file too large)
 *  - Generic AppErrors  (custom errors with a .statusCode)
 *  - Unhandled errors   → 500 Internal Server Error
 */

const env = require('../config/env');

// ─── PostgreSQL Error Code Map ────────────────────────────────────────────────
// See: https://www.postgresql.org/docs/current/errcodes-appendix.html
const PG_ERROR_MAP = {
  '23505': { status: 409, message: 'A record with that value already exists.' },
  '23502': { status: 400, message: 'A required field is missing.' },
  '23503': { status: 409, message: 'Referenced record does not exist.' },
  '23514': { status: 400, message: 'A field value violates a check constraint.' },
  '22P02': { status: 400, message: 'Invalid input syntax.' },
  '42703': { status: 400, message: 'Unknown column referenced in query.' },
  '08006': { status: 503, message: 'Database connection failure.' },
  '08001': { status: 503, message: 'Unable to connect to the database.' },
};

// ─── Error Handler ────────────────────────────────────────────────────────────
// eslint-disable-next-line no-unused-vars
const errorHandler = (err, req, res, next) => {
  // Log in all environments
  console.error(
    `[ErrorHandler] ${req.method} ${req.originalUrl} — ${err.name || 'Error'}: ${err.message}`
  );
  if (env.isDev && err.stack) {
    console.error(err.stack);
  }

  // ── PostgreSQL errors ────────────────────────────────────────────────────
  if (err.code && PG_ERROR_MAP[err.code]) {
    const mapped = PG_ERROR_MAP[err.code];
    return res.status(mapped.status).json({
      success: false,
      message: mapped.message,
      ...(env.isDev && { detail: err.detail }),
    });
  }

  // ── JWT errors ───────────────────────────────────────────────────────────
  if (err.name === 'TokenExpiredError') {
    return res.status(401).json({
      success: false,
      message: 'Token has expired. Please log in again.',
      code: 'TOKEN_EXPIRED',
    });
  }

  if (err.name === 'JsonWebTokenError') {
    return res.status(401).json({
      success: false,
      message: 'Invalid token. Authentication failed.',
      code: 'TOKEN_INVALID',
    });
  }

  // ── Multer errors ────────────────────────────────────────────────────────
  if (err.name === 'MulterError') {
    const status = err.code === 'LIMIT_FILE_SIZE' ? 413 : 400;
    return res.status(status).json({
      success: false,
      message: `File upload error: ${err.message}`,
    });
  }

  // ── Custom AppError (thrown with a statusCode property) ──────────────────
  if (err.statusCode) {
    return res.status(err.statusCode).json({
      success: false,
      message: err.message,
      ...(err.errors && { errors: err.errors }),
    });
  }

  // ── Validation errors from express-validator (rare fallthrough) ──────────
  if (err.name === 'ValidationError') {
    return res.status(422).json({
      success: false,
      message: err.message,
    });
  }

  // ── 404 Not Found (generated by app.js for unknown routes) ───────────────
  if (err.status === 404) {
    return res.status(404).json({
      success: false,
      message: err.message || 'The requested resource was not found.',
    });
  }

  // ── Unhandled / generic error ─────────────────────────────────────────────
  return res.status(500).json({
    success: false,
    message: env.isProd
      ? 'An unexpected internal error occurred. Please try again later.'
      : err.message || 'Internal Server Error',
    ...(env.isDev && { stack: err.stack }),
  });
};

module.exports = { errorHandler };
